import XCTest

@MainActor
final class PreviouslyDirectedTests: XCTestCase {
    func testOlderRetryCannotBypassNewerProgressInFlight() async throws {
        let driver = QADriver(test: self, configuration: try QAConfiguration())
        defer { driver.attachEvidence(name: "retry-during-newer-progress"); driver.app.terminate() }
        try await driver.begin()
        let before = try await driver.oracle.state("fixture-a")
        let initial = try XCTUnwrap(before.episodes(1001))
        try driver.openAnime()
        try await driver.oracle.fault("before-commit", account: "fixture-a", remaining: 3)
        try driver.markNext()
        try driver.assertProgress(initial + 1)
        try await driver.oracle.waitForFault("before-commit", path: "/me/progress", account: "fixture-a", inFlight: false, timeout: 10)
        try driver.openProfile()
        try driver.assertValue(String(initial + 1), identifier: "qa.sync.pending.progress.1001")
        try driver.tap("qa.profile.done")

        try driver.openAnime()
        try await driver.oracle.fault("delay", account: "fixture-a", delayMs: 12_000)
        driver.record("fault", "/me/progress", "completed", "Hold newer progress before commit for a controlled 12 seconds.")
        try driver.markNext()
        try driver.assertProgress(initial + 2)
        try await driver.oracle.waitForFault("delay", path: "/me/progress", account: "fixture-a", inFlight: true)
        let held = try await driver.oracle.state("fixture-a")
        XCTAssertEqual(held.episodes(1001), initial)
        try driver.openProfile()
        try driver.assertValue(String(initial + 1), identifier: "qa.sync.pending.progress.1001")
        try await driver.oracle.waitForFault("delay", path: "/me/progress", account: "fixture-a", inFlight: true)
        try driver.tap("qa.sync.retry.progress.1001")
        driver.record("retry-older-in-flight", "qa.sync.retry.progress.1001", "completed", "Actual older Retry tapped while newer server write remained in flight.")
        let final = try await driver.oracle.waitForEpisodes(initial + 2, mediaID: 1001, account: "fixture-a", timeout: 20)
        XCTAssertEqual(final.progressCommits, before.progressCommits + 1, "An obsolete Retry bypassed the lane and committed an intermediate old value.")
        // Leave no delayed request alive to mutate the next case's freshly reset account.
        try await driver.oracle.waitForFault("delay", path: "/me/progress", account: "fixture-a", inFlight: false, timeout: 30)
        let settled = try await driver.oracle.state("fixture-a")
        XCTAssertEqual(settled.episodes(1001), initial + 2)
        XCTAssertEqual(settled.progressCommits, before.progressCommits + 1)
        try driver.assertAbsent("qa.sync.pending.progress.1001")
        try driver.tap("qa.profile.done")
        try driver.openAnime()
        try driver.assertProgress(initial + 2)
    }

    func testAcceptedNewerProgressRetiresOlderFailedRetry() async throws {
        let driver = QADriver(test: self, configuration: try QAConfiguration())
        defer { driver.attachEvidence(name: "obsolete-progress-retry"); driver.app.terminate() }
        try await driver.begin()
        let before = try await driver.oracle.state("fixture-a")
        let initial = try XCTUnwrap(before.episodes(1001))
        try driver.openAnime()
        // APIClient permits two retries: all three attempts fail before any commit.
        try await driver.oracle.fault("before-commit", account: "fixture-a", remaining: 3)
        driver.record("fault", "/me/progress", "completed", "Reject initial write and both automatic retries before commit.")
        try driver.markNext()
        try driver.assertProgress(initial + 1)
        try await driver.oracle.waitForFault("before-commit", path: "/me/progress", account: "fixture-a", inFlight: false, timeout: 10)
        let failed = try await driver.oracle.state("fixture-a")
        XCTAssertEqual(failed.episodes(1001), initial)
        try driver.openProfile()
        try driver.assertValue(String(initial + 1), identifier: "qa.sync.pending.progress.1001")
        try driver.tap("qa.profile.done")

        try driver.openAnime()
        try driver.assertProgress(initial + 1)
        try driver.markNext()
        try driver.assertProgress(initial + 2)
        _ = try await driver.oracle.waitForEpisodes(initial + 2, mediaID: 1001, account: "fixture-a")
        try driver.openProfile()
        try driver.assertAbsent("qa.sync.pending.progress.1001")
        try driver.assertAbsent("qa.sync.retry.progress.1001")
        driver.record("assert-obsolete-retry", "progress.1001", "passed", "Accepted newer value retired the old failed intent.")

        driver.app.terminate()
        try await driver.launch()
        try driver.openAnime()
        try driver.assertProgress(initial + 2)
        let final = try await driver.oracle.state("fixture-a")
        XCTAssertEqual(final.episodes(1001), initial + 2)
        XCTAssertEqual(final.progressCommits, before.progressCommits + 1)
    }

    func testUpdatedFailureRetryUsesNewestIntent() async throws {
        let driver = QADriver(test: self, configuration: try QAConfiguration())
        defer { driver.attachEvidence(name: "latest-failure-retry"); driver.app.terminate() }
        try await driver.begin()
        let before = try await driver.oracle.state("fixture-a")
        let initial = try XCTUnwrap(before.episodes(1001))
        try driver.openAnime()
        for offset in 1...2 {
            try await driver.oracle.fault("before-commit", account: "fixture-a", remaining: 3)
            driver.record("fault", "/me/progress", "completed", "Reject all three attempts for episode \(initial + offset).")
            try driver.markNext()
            try driver.assertProgress(initial + offset)
            try await driver.oracle.waitForFault("before-commit", path: "/me/progress", account: "fixture-a", inFlight: false, timeout: 10)
            try driver.openProfile()
            try driver.assertValue(String(initial + offset), identifier: "qa.sync.pending.progress.1001")
            if offset == 1 {
                try driver.tap("qa.profile.done")
                try driver.openAnime()
                try driver.assertProgress(initial + 1)
            }
        }
        let failed = try await driver.oracle.state("fixture-a")
        XCTAssertEqual(failed.episodes(1001), initial)
        let failedRequests = try await driver.oracle.waitForRequests(6, method: "PUT", path: "/me/progress", account: "fixture-a")
        let older = try stableStamp(Array(failedRequests.prefix(3)))
        let newer = try stableStamp(Array(failedRequests.suffix(3)))
        XCTAssertNotEqual(newer.operationID, older.operationID, "A changed intent reused the old operation ID.")
        XCTAssertEqual(newer.writerID, older.writerID)
        XCTAssertGreaterThan(newer.sequence, older.sequence)
        try driver.tap("qa.sync.retry.progress.1001")
        _ = try await driver.oracle.waitForEpisodes(initial + 2, mediaID: 1001, account: "fixture-a")
        try driver.assertAbsent("qa.sync.pending.progress.1001")
        let retried = try await driver.oracle.state("fixture-a")
        XCTAssertEqual(retried.episodes(1001), initial + 2, "A failure row retained the first write's obsolete retry closure.")
        XCTAssertEqual(retried.progressCommits, before.progressCommits + 1)
        let allRequests = try await driver.oracle.waitForRequests(7, method: "PUT", path: "/me/progress", account: "fixture-a")
        XCTAssertEqual(try stableStamp(Array(allRequests.dropFirst(3))), newer, "Retry minted a different operation for the same pending intent.")
        try driver.tap("qa.profile.done")
        try driver.openAnime()
        try driver.assertProgress(initial + 2)
        driver.record("assert-latest-retry", "progress.1001", "passed", "Updated failure retried the newest value exactly once.")
    }

    func testFailedProgressReplayRetainsMutationIdentityAcrossRelaunch() async throws {
        let driver = QADriver(test: self, configuration: try QAConfiguration())
        defer { driver.attachEvidence(name: "persistent-progress-operation"); driver.app.terminate() }
        try await driver.begin()
        let before = try await driver.oracle.state("fixture-a")
        let initial = try XCTUnwrap(before.episodes(1001))
        try driver.openAnime()
        try await driver.oracle.fault("before-commit", account: "fixture-a", remaining: 3)
        try driver.markNext()
        try await driver.oracle.waitForFault("before-commit", path: "/me/progress", account: "fixture-a", inFlight: false, timeout: 10)
        try driver.openProfile()
        try driver.assertValue(String(initial + 1), identifier: "qa.sync.pending.progress.1001")
        let failed = try await driver.oracle.waitForRequests(3, method: "PUT", path: "/me/progress", account: "fixture-a")
        let operation = try stableStamp(failed)
        driver.app.terminate()
        try await driver.launch()
        try driver.openProfile()
        try driver.assertValue(String(initial + 1), identifier: "qa.sync.pending.progress.1001")
        try driver.tap("qa.sync.retry.progress.1001")
        let final = try await driver.oracle.waitForEpisodes(initial + 1, mediaID: 1001, account: "fixture-a")
        let replayed = try await driver.oracle.waitForRequests(4, method: "PUT", path: "/me/progress", account: "fixture-a")
        XCTAssertEqual(try stableStamp(replayed), operation, "Cold launch minted a second identity for the persisted failed intent.")
        XCTAssertEqual(final.progressCommits, before.progressCommits + 1)
        try driver.tap("qa.profile.done")
        try driver.openAnime()
        try driver.assertProgress(initial + 1)
        driver.record("assert-persistent-operation", "progress.1001", "passed", "Three rejected attempts and the restored Retry action retained the same operation, writer and sequence.")
    }

    func testProgressUndoConvergesAcrossTabsAndRelaunch() async throws {
        let driver = QADriver(test: self, configuration: try QAConfiguration())
        defer { driver.attachEvidence(name: "progress-undo"); driver.app.terminate() }
        try await driver.begin()
        let before = try await driver.oracle.state("fixture-a")
        let initial = try XCTUnwrap(before.episodes(1001))
        try driver.openAnime()
        try driver.assertProgress(initial)
        try driver.markNext()
        try driver.assertProgress(initial + 1)
        _ = try await driver.oracle.waitForEpisodes(initial + 1, mediaID: 1001, account: "fixture-a")
        try driver.tap("qa.undo")
        try driver.assertProgress(initial)
        _ = try await driver.oracle.waitForEpisodes(initial, mediaID: 1001, account: "fixture-a")
        try driver.navigate("home")
        try driver.openAnime()
        try driver.assertProgress(initial)
        driver.app.terminate()
        try await driver.launch()
        try driver.openAnime()
        try driver.assertProgress(initial)
        let after = try await driver.oracle.state("fixture-a")
        XCTAssertEqual(after.progress, before.progress)
        XCTAssertEqual(after.ownership, before.ownership)
    }

    func testRapidProgressThenBackgroundRetainsLatestIntent() async throws {
        let driver = QADriver(test: self, configuration: try QAConfiguration())
        defer { driver.attachEvidence(name: "rapid-progress"); driver.app.terminate() }
        try await driver.begin()
        let before = try await driver.oracle.state("fixture-a")
        let initial = try XCTUnwrap(before.episodes(1001))
        try driver.openAnimeEpisodes()
        for _ in 0..<3 { try driver.tap("qa.progress.increment.1001") }
        try driver.assertProgress(initial + 3)
        XCUIDevice.shared.press(.home)
        driver.record("background", "system.home", "completed")
        driver.app.activate()
        try driver.requireReady()
        try driver.assertProgress(initial + 3)
        _ = try await driver.oracle.waitForEpisodes(initial + 3, mediaID: 1001, account: "fixture-a")
        driver.app.terminate()
        try await driver.launch()
        try driver.openAnime()
        try driver.assertProgress(initial + 3)
    }

    func testLateSearchCannotOverwriteNewerQuery() async throws {
        let driver = QADriver(test: self, configuration: try QAConfiguration())
        defer { driver.attachEvidence(name: "late-search"); driver.app.terminate() }
        try await driver.begin()
        let before = try await driver.oracle.state("fixture-a")
        try driver.navigate("discover")
        try await driver.oracle.fault("delay", account: "fixture-a", path: "/search", delayMs: 1_500)
        driver.record("fault", "/search", "completed", "First response delayed 1500ms; replacement query is immediate.")
        try driver.replaceText("anime", in: "qa.search.field")
        try await driver.oracle.waitForFault("delay", path: "/search", account: "fixture-a", inFlight: true)
        driver.record("fault-dispatched", "/search", "completed", "Scratch server confirmed the old query is in flight.")
        try driver.replaceText("plan", in: "qa.search.field")
        try driver.require("qa.search.result.qa-plan")
        try await driver.oracle.waitForFault("delay", path: "/search", account: "fixture-a", inFlight: false)
        driver.record("fault-completed", "/search", "completed", "Scratch server confirmed the old response completed.")
        XCTAssertTrue(driver.element("qa.search.result.qa-plan").exists)
        XCTAssertFalse(driver.element("qa.search.result.qa-anime").exists, "An old result replaced the new query.")
        let longQuery = String(repeating: "x", count: 120)
        try driver.replaceText(longQuery, in: "qa.search.field")
        try driver.replaceText(longQuery, in: "qa.search.field")
        try driver.replaceText("QA", in: "qa.search.field")
        try driver.require("qa.search.result.qa-anime")
        driver.record("assert-long-query-replacement", "qa.search.field", "passed", "120 characters entered exactly twice, then explicitly cleared for QA.")
        try driver.dismissKeyboard()
        try driver.navigate("library")
        let after = try await driver.oracle.state("fixture-a")
        XCTAssertEqual(after.progress, before.progress)
        XCTAssertEqual(after.ownership, before.ownership)
    }

    func testCommittedWriteWithLostResponseHasOneEffect() async throws {
        let driver = QADriver(test: self, configuration: try QAConfiguration())
        defer { driver.attachEvidence(name: "lost-response"); driver.app.terminate() }
        try await driver.begin()
        let before = try await driver.oracle.state("fixture-a")
        let initial = try XCTUnwrap(before.episodes(1001))
        try driver.openAnime()
        try await driver.oracle.fault("drop-after-commit", account: "fixture-a")
        driver.record("fault", "/me/progress", "completed", "One response dropped after canonical commit.")
        try driver.markNext()
        try driver.assertProgress(initial + 1)
        let committed = try await driver.oracle.waitForEpisodes(initial + 1, mediaID: 1001, account: "fixture-a")
        XCTAssertEqual(committed.progressCommits, before.progressCommits + 1, "Duplicate logical progress effects are not acceptable.")
        let attempts = try await driver.oracle.waitForRequests(2, method: "PUT", path: "/me/progress", account: "fixture-a")
        _ = try stableStamp(attempts)
        driver.app.terminate()
        try await driver.launch()
        try driver.openAnime()
        try driver.assertProgress(initial + 1)
        let final = try await driver.oracle.state("fixture-a")
        XCTAssertEqual(final.episodes(1001), initial + 1)
        XCTAssertEqual(final.progressCommits, before.progressCommits + 1)
    }

    private func stableStamp(_ requests: [QAOracle.RequestRecord]) throws -> QAOracle.MutationRecord {
        let first = try XCTUnwrap(requests.first?.mutation, "An owned progress write omitted mutation metadata.")
        XCTAssertNotNil(UUID(uuidString: first.operationID))
        XCTAssertNotNil(UUID(uuidString: first.writerID))
        XCTAssertEqual(first.operationID, first.operationID.lowercased())
        XCTAssertEqual(first.writerID, first.writerID.lowercased())
        XCTAssertGreaterThan(first.sequence, 0)
        for request in requests { XCTAssertEqual(request.mutation, first, "One intent changed identity between HTTP attempts.") }
        return first
    }

    func testAccountSwitchDoesNotExposePreviousLibrary() async throws {
        let driver = QADriver(test: self, configuration: try QAConfiguration())
        defer { driver.attachEvidence(name: "account-switch"); driver.app.terminate() }
        try await driver.begin()
        try await driver.oracle.reset("fixture-b")
        try driver.navigate("home")
        try driver.tap("qa.profile.open")
        try driver.tap("qa.signout")
        try driver.tap("qa.signout.confirm")
        try driver.replaceText("fixture-b", in: "qa.signin.dev.field")
        try driver.tap("qa.signin.dev.submit")
        try driver.require("qa.account.fixture-b")
        try driver.navigate("library")
        try driver.require("qa.show.qa-plan")
        XCTAssertFalse(driver.element("qa.show.qa-anime").exists)
        XCTAssertFalse(driver.element("qa.show.qa-tv").exists)
        let a = try await driver.oracle.state("fixture-a")
        let b = try await driver.oracle.state("fixture-b")
        XCTAssertEqual(a.ownership, ["qa-anime", "qa-tv"])
        XCTAssertEqual(b.ownership, ["qa-plan"])
        driver.app.terminate()
        try await driver.launch(account: "fixture-b")
        try driver.require("qa.account.fixture-b")
        try driver.navigate("library")
        try driver.require("qa.show.qa-plan")
        XCTAssertFalse(driver.element("qa.show.qa-anime").exists)
        XCTAssertFalse(driver.element("qa.show.qa-tv").exists)
        driver.record("assert-isolation", "fixture-b", "passed", "A's titles absent before and after B relaunch.")
    }
}
